### ISSUE TITLE
Add trusty repos?

### ISSUE THREAD

**Issue by joshpurvis** [HorizenOfficial/repo#1]
I'm running ubuntu trusty and can't seem to install via deb packages. I believe this is because there are no trusty packages. Would it be possible to add? Or is there some dependency that prevents it?

**Comment by cronicc** [comment]
I've added trusty to the list of distributions in the repository, as the .debs are packaged on xenial it's possible you might run into dependency issues.

I've tested the zen 2.0.11 package on the trusty docker image and it works there, please report back here if it doesn't work for you.
